language: node_js
node_js:
  - "7"
before_script:
  - npm install -g backslide && npm i -g gitmoji-cli
script:
  - cd src/slides/
  - bs e -o ../../docs
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: docs
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
